config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "users#index"
  resources :users do
    resources :events
    resources :puzzles
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: { message: 'が入力されていません' }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    # @events = event.includes(:user)
    @user = User.find(params[:user_id])
    event_datas = Event.where(user_id: params[:user_id])

    @datas= [];
    event_datas.each do |data|
      @datas += [
        'title' => data[:title],
        'content' => data[:content],
        'start' => data[:start_date],
        'end' => data[:end_date],
        'url' => "/users/#{@user.id}/events/#{data[:id]}",
        'color' => '#98d6ea',
        'textColor' => 'black',
        'borderColor' => '#007bff'
      ]
    end
    @puzzles = Puzzle.where(user_id: current_user)
    if @puzzles == []
      9.times do
        Puzzle.create(user_id: @user.id, task: "タスクが入力されていません")
      end
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @user = User.find(params[:user_id])
  end

  # GET /events/new
  def new
    @event = Event.new
    @events = Event.where(user_id: current_user)
  end

  # GET /events/1/edit
  def edit
    @user = User.find(params[:user_id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to new_user_event_path(current_user), notice: 'event was successfully created.' }
        format.json
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to user_events_path(current_user), notice: 'event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to new_user_event_path(current_user), notice: 'event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :content, :start_date, :end_date).merge(user_id: current_user.id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.haml
.event
  .event__new
    %p.event__new--header タスクの編集
    .event__new--render
      = form_for @event, url: user_event_path do |f|
        - if @event.errors.any?
          #error_explanation
            %ul
              - @event.errors.full_messages.each do |message|
                %li= message

        .field.event__form--field
          = f.label :タイトル, class: "event__form--label"
          = f.text_field :title, class: "event__form--title--input"
        .field.event__form--field
          = f.label :メモ, class: "event__form--label"
          = f.text_area :content, class: "event__form--content"
        .field.event__form--field
          = f.label :開始日, class: "event__form--label"
          = f.datetime_select :start_date
        .field.event__form--field
          = f.label :終了日, class: "event__form--label"
          = f.datetime_select :end_date
        .actions
          = f.submit '編集', class: "event__form--btn"

    = link_to 'カレンダーに戻る', user_events_path(@user), class: "index--back--btn"

app/views/events/index.html.haml
.user__menu
  .user--info
    .user--info__image
      = image_tag @user.image.url, class: 'icon_image', alt: 'default.png'
    
    .user--info__name
      %p= @user.nickname
      -if user_signed_in? && @user.id == current_user.id
        = link_to "プロフィール編集", edit_user_path(current_user), class: "user--info__edit", method: :get
        = link_to "タスクの追加", new_user_event_path(current_user), class: "user--info__edit"
      = link_to "タスクパズル", user_puzzles_path(@user), class: "user--info__edit"

 
.calendar
  #calendar

:javascript
  window.event_datas = #{raw @datas.to_json};

app/views/events/new.html.haml
.event
  .event__new
    %p.event__new--header タスクの追加
    .event__new--render
      = form_for @event, url: user_events_path, remote: true do |f|
        - if @event.errors.any?
          #error_explanation
            %ul
              - @event.errors.full_messages.each do |message|
                %li= message

        .field.event__form--field
          = f.label :タイトル, class: "event__form--label"
          = f.text_field :title, class: "event__form--title--input"
        .field.event__form--field
          = f.label :メモ, class: "event__form--label"
          = f.text_area :content, class: "event__form--content"
        .field.event__form--field
          = f.label :開始日, class: "event__form--label"
          = f.datetime_select :start_date
        .field.event__form--field
          = f.label :終了日, class: "event__form--label"
          = f.datetime_select :end_date
        .actions
          = f.submit '追加', class: "event__form--btn"

    .event__index--title 
      %p #{current_user.nickname}さんのタスク一覧

    %table
      %thead
        %tr.event__unit--header
          %th.event__unit--header--title タイトル
          %th.event__unit--header--content メモ
          %th.event__unit--header--start_date 開始日
          %th.event__unit--header--end_date 終了日
          %th
          %th
          %th


      %tbody.event__units
        - @events.each do |event|
          %tr.event__unit
            %td.event__unit--title= event.title
            %td.event__unit--content= event.content
            %td.event__unit--start_date= event.start_date.to_s(:datetime_jp)
            %td.event__unit--end_date= event.end_date.to_s(:datetime_jp)
            %td.event__unit--btn=link_to "詳細", user_event_path(current_user,event),class: "underline-none"
            %td.event__unit--btn=link_to "編集", edit_user_event_path(current_user,event),class: "underline-none"
            %td.event__unit--btn.delete--btn=link_to "削除", user_event_path(current_user,event), method: :delete, remote: true,class: "underline-none color-white"

app/views/events/show.html.haml
.event
  .event__show

    %p
      %b.event__show--title タスクのタイトル:
      = @event.title
    %p
      %b.event__show--content メモ:
      = @event.content
    %p
      %b.event__show--start_date 開始日:
      = @event.start_date.to_s(:datetime_jp)
    %p
      %b.event__show--end_date 終了日:
      = @event.end_date.to_s(:datetime_jp)
    -if user_signed_in? && @user.id == current_user.id
      = link_to '編集', edit_user_event_path(current_user,@event), class:"event__edit--btn"
    = link_to 'カレンダーに戻る', user_events_path(@user), class: "index--back--btn"