config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "users#index"
  resources :users do
    resources :events
    resources :puzzles
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myprogress2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body{"data-turbolinks" => "false"}

    .header
      %ul.header__menus
        %li.header__menu
          .fas.fa-dog.fa-lg
          = link_to "MyProgress", root_path, class: "header__menu--link"
        %li.header__menu
          .fas.fa-users.fa-lg
          = link_to "ユーザー一覧", root_path, class: "header__menu--link"
        -if user_signed_in?
          %li.header__menu
            .fas.fa-sign-out-alt.fa-lg
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__menu--link"
          %li.header__menu.myname
            .fas.fa-user.fa-lg
            = link_to current_user.nickname, user_events_path(current_user), class: "header__menu--link"
        -else
          %li.header__menu
            .fas.fa-sign-in-alt.fa-lg
            = link_to "ログイン", new_user_session_path, class: "header__menu--link"
        
        #bars
          .fas.fa-bars.fa-lg

      #side__menu
        .side__menu--close#close
          .fas.fa-times.fa-lg
        %ul.side__menus
          %li.side__menu
            .fas.fa-dog.fa-lg
            = link_to "MyProgress", root_path, class: "side__menu--link"
          -if user_signed_in?
            %li.side__menu
              .fas.fa-sign-out-alt.fa-lg
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "side__menu--link"
            %li.side__menu.myname
              .fas.fa-user.fa-lg
              = link_to current_user.nickname, root_path, class: "side__menu--link"
          -else
            %li.side__menu
              .fas.fa-sign-in-alt.fa-lg
              = link_to "ログイン", new_user_session_path, class: "side__menu--link"
          %li.side__menu
            .fas.fa-users.fa-lg
            = link_to "ユーザー一覧", root_path, class: "side__menu--link"

    = yield