config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "users#index"
  resources :users do
    resources :events
    resources :puzzles
  end

end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  belongs_to :user

end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @puzzles = Puzzle.where(user_id: @user)
  end

  def edit
    @user = User.find(params[:user_id])
    @puzzle = Puzzle.find(params[:id])
  end
  
  def create
    @puzzle = Puzzle.create(puzzle_params)
    redirect_to user_puzzles_path(current_user)
  end

  def update
    @puzzle = Puzzle.find(params[:id])
    if @puzzle.update(puzzle_params)
      redirect_to user_puzzles_path(current_user)
    else
      render :edit
    end
  end
  
private
  def puzzle_params
    params.require(:puzzle).permit(:task, :square).merge(user_id: current_user.id)
  end
  
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/puzzles/edit.html.haml
.user__menu
  .user--info
    .user--info__image
      = image_tag @user.image.url, class: 'icon_image', alt: 'default.png'
    
    .user--info__name
      %p= @user.nickname
      -if user_signed_in? && @user.id == current_user.id
        = link_to "プロフィール編集", edit_user_path(current_user), class: "user--info__edit", method: :get
        = link_to "タスクの追加", new_user_event_path(current_user), class: "user--info__edit"
        = link_to "タスクパズル", user_puzzles_path(current_user), class: "user--info__edit"

.task--puzzle__edit
  %p.task--puzzle__edit--header タスクパズルの編集
  .task--puzzle__edit--unit
    = form_for @puzzle, url: user_puzzle_path, method: :patch do |f|
      - if @puzzle.errors.any?
        #error_explanation
          %ul
            - @puzzle.errors.full_messages.each do |message|
              %li= message

      .field.puzzle__form--field
        = f.label :タスク：, class: "puzzle__form--label"
        = f.text_field :task, class: "puzzle__form--title--input"
      .actions
        = f.submit '編集', class: "puzzle__form--btn"
        = link_to "キャンセル", user_puzzles_path(current_user), class: "puzzle--cancel"

app/views/puzzles/index.html.haml
.user__menu
  .user--info
    .user--info__image
      = image_tag @user.image.url, class: 'icon_image', alt: 'default.png'
    
    .user--info__name
      %p= @user.nickname
      -if user_signed_in? && @user.id == current_user.id
        = link_to "プロフィール編集", edit_user_path(current_user), class: "user--info__edit", method: :get
        = link_to "タスクの追加", new_user_event_path(current_user), class: "user--info__edit"
      = link_to "タスクパズル", user_puzzles_path(@user), class: "user--info__edit"

.task__index
  .task__index--unit1
    %p タスク1:
    %p= @puzzles[0].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[0]), class: "task__index--edit--link"
      -if @puzzles[0].square
        = link_to "",user_puzzle_path(@user,@puzzles[0],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[0],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'



  .task__index--unit2
    %p タスク2:
    %p= @puzzles[1].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[1]), class: "task__index--edit--link"
      -if @puzzles[1].square
        = link_to "",user_puzzle_path(@user,@puzzles[1],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[1],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'


  .task__index--unit3
    %p タスク3:
    %p= @puzzles[2].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[2]), class: "task__index--edit--link"
      -if @puzzles[2].square
        = link_to "",user_puzzle_path(@user,@puzzles[2],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[2],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'


  .task__index--unit4
    %p タスク4:
    %p= @puzzles[3].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[3]), class: "task__index--edit--link"
      -if @puzzles[3].square
        = link_to "",user_puzzle_path(@user,@puzzles[3],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[3],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'

    
  .task__index--unit5
    %p タスク5:
    %p= @puzzles[4].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[4]), class: "task__index--edit--link"
      -if @puzzles[4].square
        = link_to "",user_puzzle_path(@user,@puzzles[4],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[4],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'


  .task__index--unit6
    %p タスク6:
    %p= @puzzles[5].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[5]), class: "task__index--edit--link"
      -if @puzzles[5].square
        = link_to "",user_puzzle_path(@user,@puzzles[5],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[5],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'


  .task__index--unit7
    %p タスク7:
    %p= @puzzles[6].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[6]), class: "task__index--edit--link"
      -if @puzzles[6].square
        = link_to "",user_puzzle_path(@user,@puzzles[6],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[6],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'

  
  .task__index--unit8
    %p タスク8:
    %p= @puzzles[7].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[7]), class: "task__index--edit--link"
      -if @puzzles[7].square
        = link_to "",user_puzzle_path(@user,@puzzles[7],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[7],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'

  .task__index--unit9
    %p タスク9:
    %p= @puzzles[8].task
    .task__index--edit
    -if user_signed_in? && @user.id == current_user.id
      = link_to "編集", edit_user_puzzle_path(current_user,@puzzles[8]), class: "task__index--edit--link"
      -if @puzzles[8].square
        = link_to "",user_puzzle_path(@user,@puzzles[8],puzzle: {square: false}), method: :put, remote: true, class: 'fa fa-check-square fa-lg puzzle-check'
      - else
        = link_to "",user_puzzle_path(@user,@puzzles[8],puzzle: {square: true}), method: :put, remote: true, class: 'fa fa-square fa-lg puzzle-check'
.canvas--wrapper

  %canvas#stage{:height => "540", :width => "540"}
  %canvas#line{:height => "540", :width => "540"}

  -if @puzzles[0].square  
    %canvas#top-left.disabled{:height => "180", :width => "180"}
  -else
    %canvas#top-left{:height => "180", :width => "180"}

  -if @puzzles[1].square
    %canvas#top-center.disabled{:height => "180", :width => "180"}
  -else
    %canvas#top-center{:height => "180", :width => "180"}

  -if @puzzles[2].square  
    %canvas#top-right.disabled{:height => "180", :width => "180"}
  -else
    %canvas#top-right{:height => "180", :width => "180"}

  -if @puzzles[3].square  
    %canvas#center-left.disabled{:height => "180", :width => "180"}
  -else
    %canvas#center-left{:height => "180", :width => "180"}

  -if @puzzles[4].square  
    %canvas#center-center.disabled{:height => "180", :width => "180"}
  -else
    %canvas#center-center{:height => "180", :width => "180"}

  -if @puzzles[5].square  
    %canvas#center-right.disabled{:height => "180", :width => "180"}
  -else
    %canvas#center-right{:height => "180", :width => "180"}

  -if @puzzles[6].square  
    %canvas#bottom-left.disabled{:height => "180", :width => "180"}
  -else
    %canvas#bottom-left{:height => "180", :width => "180"}

  -if @puzzles[7].square  
    %canvas#bottom-center.disabled{:height => "180", :width => "180"}
  -else
    %canvas#bottom-center{:height => "180", :width => "180"}

  -if @puzzles[8].square  
    %canvas#bottom-right.disabled{:height => "180", :width => "180"}
  -else
    %canvas#bottom-right{:height => "180", :width => "180"}